### ISSUE TITLE
Can't see MC -> IRC Chat

### ISSUE THREAD

**Issue by mksvco** [NuclearW/Farion#4]
I'm using EssentialsChat, it's not local, and I can see IRC -> MC fine.

**Comment by NuclearW** [comment]
Are you also using Factions, and specifically the faction-relation color feature for chat?

**Comment by mksvco** [comment]
Nope.

**Comment by NuclearW** [comment]
I don't use EssentialsChat, so I don't know how it works exactly, are there channels? Any chat that doesn't go to all users won't go to IRC, for instance.

**Comment by mksvco** [comment]
No, there are no channels. Is it possible it's because of the custom chat setup (ie colors and formatting)?

**Comment by NuclearW** [comment]
I'm not sure, I've not seen this issue from others who use EssentialsChat.

What all plugins do you use?

**Comment by mksvco** [comment]
22:36:45 [INFO] Plugins (35): Kits, Shortify, MCBouncer, NoCheatPlus, WorldEdit, ChatHighlighter, VoxelSniper, Heads, Vault, PluginReloader, PermissionsEx, Multiverse-Core, AntiInvisibilityPotion, WorldGuard, DispenserRefill, dynmap, ModReq, FishStats, AutoMessage, WorldGuardFlags, CustomMessages, HawkEye, CommandHelper, DeathMessages, GroupList, Engrave, Essentials, WorldBorder, EssentialsSpawn, Dynmap-Essentials, Multiverse-Portals, Multiverse-Inventories, Multiverse-NetherPortals, EssentialsChat, TagAPI

http://puu.sh/2oGGZ is what my console is like

**Comment by NuclearW** [comment]
I'm not sure.  The best I can guess is that you try it while removing plugins one at a time to identify the one that is getting in the way.
